[config]
# Directory where the podcasts will be downloaded.
# Each podcast will be a subdirectory under this directory.
media_dir = "/home/salil/Music"
# Music player to be used for "play" action.
player = "/usr/bin/mpv"
# Playback speed for the "play" action.
playback_speed = 1.5

[[podcasts]]
id = "BegToDiffer"
url = "https://audioboom.com/channels/5114288.rss"

[[podcasts]]
id = "WashingtonWeek"
url = "http://feeds.pbs.org/pbs/weta/washingtonweek-audio"

[[podcasts]]
id = "UpFirst"
url = "https://feeds.npr.org/510318/podcast.xml"
