# Media directory to store the files
media_dir = "<media_dir>"

# List of feeds of your podcasts
[podcasts]
BegToDiffer = "https://feeds.megaphone.fm/WWO9642284243"
TheEconomist = "https://rss.acast.com/theeconomisteditorspicks"
LeftRightAndCenter = "https://leftrightandcenter-feed.kcrw.com"
NewsHour = "https://www.pbs.org/newshour/feeds/rss/podcasts/show"
WashingtonWeek = "http://feeds.pbs.org/pbs/weta/washingtonweek-audio"
PoliticalGabFest = "https://feeds.megaphone.fm/slatespoliticalgabfest"
TheBulwark = "https://feeds.megaphone.fm/WWO9257218156"
Neoliberal = "https://neolibpodcast.libsyn.com/rss"
UpFirst = "https://feeds.npr.org/510318/podcast.xml"
WorldNewsThisWeek = "https://feeds.megaphone.fm/ESP8938831552"
