media_dir = "/home/salil/Music"

[podcasts]
BegToDiffer = "https://audioboom.com/channels/5114288.rss"
WashingtonWeek = "http://feeds.pbs.org/pbs/weta/washingtonweek-audio"
UpFirst = "https://feeds.npr.org/510318/podcast.xml"
GPS = "https://feeds.megaphone.fm/WMHY7703459968"
TheRealTime = "https://feeds.megaphone.fm/WMHY1886903044"
TheRemnant = "https://feeds.megaphone.fm/DISPME4897766830"
